### ISSUE TITLE
metacpan pod rendering doesn't work for C<$tb-E<gt>rule( '-', '+')>

### ISSUE THREAD

**Issue by p-alik** [shlomif/Text-Table#5]
[metacpan](https://metacpan.org/pod/release/SHLOMIF/Text-Table-1.130/lib/Text/Table.pm#rule()) renders it to `$tb-<rule( '-', '+')`

Probably `C<< $tb-E<gt>rule( '-', '+') >>` solves the issue

**Comment by p-alik** [comment]
pardon me, it was already fixed in 1.132
https://rt.cpan.org/Public/Bug/Display.html?id=118852

**Comment by shlomif** [comment]
On Wed, 06 Jun 2018 13:13:10 +0000 (UTC)
Алексей Пастухов <notifications@github.com> wrote:

> [metacpan](https://metacpan.org/pod/release/SHLOMIF/Text-Table-1.130/lib/Text/Table.pm#rule())
> renders it to `$tb-<rule( '-', '+')`
> 
> Probably `C<< $tb-E<gt>rule( '-', '+') >>` solves the issue
> 

Hi Alexey,

1. The POD validates.

2. It is rendered fine by both pod2man and pod2xhtml.

3. It may affect other .pod docs on metacpan.

4. Please report it there as it seems to be their bug.

5. Can I close this issue?

6. See http://www.shlomifish.org/humour.html#real_programmers_dont_write .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Networking Clients - http://shlom.in/net-clients

He who has more is not happier than he who wants less.
    — Source unknown, via Nadav Har’El.

Please reply to list if it's a mailing list post - http://shlom.in/reply .
